// ================= HOME =================
if (document.querySelector(".faq-question")) {

const questions = document.querySelectorAll(".faq-question");

questions.forEach(btn => {
btn.addEventListener("click", () => { 

const answer = btn.nextElementSibling;


document.querySelectorAll(".faq-answer").forEach(a => {
if (a !== answer) {
a.style.maxHeight = null;
a.parentElement.classList.remove("active");
}
});

if (answer.style.maxHeight) {
answer.style.maxHeight = null;
btn.parentElement.classList.remove("active");
} else {
answer.style.maxHeight = answer.scrollHeight + "px";
btn.parentElement.classList.add("active");
}

});
});

}


// ================= UPLOAD =================
if (document.getElementById('drop-zone')) {

const dropZone = document.getElementById('drop-zone');
const fileInput = document.getElementById('file-input');
const browseBtn = document.getElementById('browse-btn');
const fileNameDisplay = document.getElementById('file-name');
const uploadForm = document.getElementById('upload-form');
const progressContainer = document.getElementById('progress-container');
const progressFill = document.getElementById('progress-fill');
const progressText = document.getElementById('progress-text');

browseBtn.addEventListener('click', () => {
fileInput.click();
});

uploadForm.onsubmit = (e) => {
if (fileInput.files.length === 0) {
e.preventDefault();
alert("Select a file first using 'Browse Files'");
return;
}
};

fileInput.onchange = function () {
if (this.files.length > 0) {
handleFiles(this.files[0]);
}
};

['dragenter', 'dragover'].forEach(eventName => {
dropZone.addEventListener(eventName, (e) => {
e.preventDefault();
dropZone.style.background = "rgba(255, 255, 255, 0.15)";
}, false);
});

['dragleave', 'drop'].forEach(eventName => {
dropZone.addEventListener(eventName, (e) => {
e.preventDefault();
dropZone.style.background = "rgba(255, 255, 255, 0.05)";
}, false);
});

dropZone.addEventListener('drop', (e) => {
const dt = e.dataTransfer;
const files = dt.files;
if (files.length > 0) {
fileInput.files = files;
handleFiles(files[0]);
}
});

function handleFiles(file) {
fileNameDisplay.innerHTML =`Selected: <strong style="color:#bf40ff">${file.name}</strong>`;
}

uploadForm.onsubmit = (e) => {

if (fileInput.files.length === 0) {
e.preventDefault();
alert("Please select a file first!");
return;
}

const file = fileInput.files[0];

const allowedTypes = ["image/jpeg", "image/png", "image/jpg", "video/mp4"];

if (!allowedTypes.includes(file.type)) {
alert("Invalid file type!");
return;
}

if (file.size > 10 * 1024 * 1024) {
alert("File too large (Max 10MB)");
return;
}

e.preventDefault();

progressContainer.style.display = 'block';

let width = 0;

const interval = setInterval(() => {

if (width >= 100) {
clearInterval(interval);
progressText.innerText = "Success! Redirecting...";

const reader = new FileReader();

reader.onload = function (e) {
localStorage.setItem("uploadedImage", e.target.result);
window.location.href = "results.html";
};

reader.readAsDataURL(fileInput.files[0]);

} else {
width += Math.floor(Math.random() * 5) + 2;
if (width > 100) width = 100;

progressFill.style.width = width + '%';
progressText.innerText = "Analyzing Media... " + width + "%";
}

}, 100);

};

}


// ================= RESULTS =================
if (document.getElementById("result-image")) {

const uploadedImage = localStorage.getItem("uploadedImage");
const resultImage = document.getElementById("result-image");

if (uploadedImage && resultImage) {
resultImage.src = uploadedImage;
}

const resultBadge = document.getElementById("result-badge");
const scorenumber = document.getElementById("score-number");
const downloadBtn = document.querySelector(".download-btn");
const againBtn = document.querySelector(".again-btn");

const isFake = Math.random() > 0.5;
const confidence = (Math.random() * 20 + 80).toFixed(1);

if (isFake) {
resultBadge.innerText = "Fake";
resultBadge.classList.add("fake");
resultBadge.classList.remove("real");
} else {
resultBadge.innerText = "Real";
resultBadge.classList.add("real");
resultBadge.classList.remove("fake");
}

scorenumber.innerText = confidence + "%";

if (againBtn) {
againBtn.onclick = () => {
localStorage.removeItem("uploadedImage");
window.location.href = "Upload.html";
};
}

if (downloadBtn) {
downloadBtn.onclick = () => {

const reportContent = `
DeepFake Detection Report
------------------------
Result: ${resultBadge.innerText}
Confidence Score: ${confidence}%
Date: ${new Date().toLocaleString()}
Generated by Catch Fake
`;

const blob = new Blob([reportContent], { type: "text/plain" });
const link = document.createElement("a");
link.href = URL.createObjectURL(blob);
link.download = "DeepFake_Report.txt";
link.click();

};
}

}
const menuToggle = document.getElementById("menu-toggle");
const navLinks = document.getElementById("nav-links");

menuToggle.onclick = () => {
  menuToggle.classList.toggle("active");
  navLinks.classList.toggle("active");
};